name: Development Build (Galaxy A50)#

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'

jobs:
  aosp-s-e:
    name: Build AOSP 12 (Enforcing)
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    runs-on: self-hosted

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    #- name: Update Debian/Ubuntu Repositories
    #  run: sudo apt-get update

    #- name: Install Debian/Ubuntu dependencies
    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --magisk --automated --device a50 --variant aosp --android 12

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50_aosp-s-e.txt

    - name: Upload kernel image artifact
      uses: actions/upload-artifact@v2
      with:
        name: AOSP 12 Kernel Image (Enforcing)
        path: 'tools/make/boot.img'
        if-no-files-found: error

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kernel Configs
        path: 'release/kernel_config_a50_aosp-s-e.txt'
        if-no-files-found: error

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'release'
        if-no-files-found: error

  aosp-s-p:
    name: Build AOSP 12 (Permissive)
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    runs-on: self-hosted

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    #- name: Update Debian/Ubuntu Repositories
    #  run: sudo apt-get update

    #- name: Install Debian/Ubuntu dependencies
    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --magisk --automated --device a50 --variant aosp --android 12 --permissive

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50_aosp-s-p.txt

    - name: Upload kernel image artifact
      uses: actions/upload-artifact@v2
      with:
        name: AOSP 12 Kernel Image (Permissive)
        path: 'tools/make/boot.img'
        if-no-files-found: error

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kernel Configs
        path: 'release/kernel_config_a50_aosp-s-p.txt'
        if-no-files-found: error

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'release'
        if-no-files-found: error

  release:
    name: Release files and configs
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    needs: [aosp-s-e, aosp-s-p]
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Roma"
        timezoneMacos: "Europe/Roma"
        timezoneWindows: "Italy Standard Time"

    - name: Merge Releases
      uses: actions/download-artifact@v2
      with:
        name: Release
        path: release

    - name: Delete build config files
      run: |
          set -eo pipefail
          rm -rf ./release/kernel_config_*.txt

    - name: Delete older release
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 12
        delete_tag_pattern: "xbeta"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload release
      uses: Hs1r1us/Release-AIO@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag
        replacesArtifacts: false
        tag_name: xbeta-${{ github.run_number }}_a50dx
        prerelease: true
        release_name: Galaxy A50 (beta-${{ github.run_number }})
        allowUpdates: true
        body_path: "./tools/make/release/a50-development.md"
        asset_files: './release'
