name: Development Build Opensuse (Galaxy A50)

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'

jobs:
  oneui:
    name: Build One UI
    runs-on: opensuse_desk

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    #- name: Install Debian/Ubuntu dependencies
    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
          ./build.sh --magisk --automated --device a50 --variant oneui

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: oneui_beta-${{ github.run_number }}
        path: 'release'
        if-no-files-found: error

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50.txt

    - name: Upload kernel image artifact
      uses: actions/upload-artifact@v2
      with:
        name: One UI Kernel Image
        path: 'tools/make/boot.img'
        if-no-files-found: error

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: One UI Kernel Config
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error

  aosp:
    name: Build Lineage/AOSP 11
    runs-on: opensuse_desk

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

   # - name: Install Debian/Ubuntu dependencies
   #   run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
          ./build.sh --magisk --automated --device a50 --variant aosp

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: aosp_beta-${{ github.run_number }}
        path: 'release'
        if-no-files-found: error

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50.txt

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: AOSP 11 Kernel Config
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error

  snowcone:
    name: Build Lineage/AOSP 12
    runs-on: opensuse_desk

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

   # - name: Install Debian/Ubuntu dependencies
   #   run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
          ./build.sh --magisk --automated --device a50 --variant aosp --android 12

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: snowcone_beta-${{ github.run_number }}
        path: 'release'
        if-no-files-found: error

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50.txt

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: AOSP 12 Kernel Config
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error

  aosp_permissive:
    name: Build Lineage/AOSP 11 - Permissive
    runs-on: opensuse_desk

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

   # - name: Install Debian/Ubuntu dependencies
   #   run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
          ./build.sh --automated --device a50 --variant aosp --permissive --magisk

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: aosp-permissive_beta-${{ github.run_number }}
        path: 'release'
        if-no-files-found: error

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50.txt

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: AOSP 11 Permissive Kernel Config
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error

  snowcone_permissive:
    name: Build Lineage/AOSP 12 - Permissive
    runs-on: opensuse_desk

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    #- name: Install Debian/Ubuntu dependencies
    #  run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          export KBUILD_BUILD_VERSION=${GITHUB_RUN_NUMBER}
          ./build.sh --automated --device a50 --variant aosp --android 12 --permissive --magisk

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname MintBeta-*.zip` ./release/

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: snowcone-permissive_beta-${{ github.run_number }}
        path: 'release'
        if-no-files-found: error

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50.txt

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: AOSP 12 Permissive Kernel Config
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error

  release:
    name: Release files and configs
    if: always()
    needs: [oneui, aosp, aosp_permissive, snowcone, snowcone_permissive]
    runs-on: opensuse_desk
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Rome"
        timezoneMacos: "Europe/Rome"
        timezoneWindows: "Italy Standard Time"

    - name: Merge One UI Release
      uses: actions/download-artifact@v2
      with:
        name: oneui_beta-${{ github.run_number }}
        path: release
      
    - name: Merge Lineage/AOSP 11 release
      uses: actions/download-artifact@v2
      with:
        name: aosp_beta-${{ github.run_number }}
        path: release

    - name: Merge Lineage/AOSP 12 release
      uses: actions/download-artifact@v2
      with:
        name: snowcone_beta-${{ github.run_number }}
        path: release

    - name: Merge Lineage/AOSP (permissive) release
      uses: actions/download-artifact@v2
      with:
        name: aosp-permissive_beta-${{ github.run_number }}
        path: release
      
    - name: Merge Lineage/AOSP 12 (permissive) release
      uses: actions/download-artifact@v2
      with:
        name: snowcone-permissive_beta-${{ github.run_number }}
        path: release

    - name: Delete older release
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 12
        delete_tag_pattern: "xbeta"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload release
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag
        tag_name: xbeta-${{ github.run_number }}_a50dx
        prerelease: true
        release_name: Galaxy A50 (beta-${{ github.run_number }})
        body_path: "./tools/make/release/a50-development.md"
        asset_files: './release'
